##############################################
# !!! Datei umbenennen !!!              ######
# secrets_copy.toml -> secrets.toml     ######
##############################################

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "kuhnnad1@zhaw.students.ch"
password = "ACHVX-IFMDQ-OGUIL-ZPLKH"
